DESIGN=cdh_tsat5_system
DESDIR=C:\Users\Joseph Howarth\Documents\UMSATS\cdh-tsat5\cdh-tsat5-libero\designer\cdh_tsat5_system
TARGET_DIR=C:\Users\Joseph Howarth\Documents\UMSATS\cdh-tsat5\cdh-tsat5-libero\designer\cdh_tsat5_system
FAM=SmartFusion2
DIE=PA4M1000_N
PACKAGE=tq144
PINRPT_BY_NAME=1
PINRPT_BY_NUMBER=1
BANK_REPORT=1
IOREG_REPORT=1
